### ISSUE TITLE
Peer-review system

### ISSUE THREAD

**Issue by dbosk** [OpenSecEd/infosec#19]
There should be a way to streamline peer-reviewing in the course. Maybe the following can be useful:
- [Open Journal Systems](https://pkp.sfu.ca/ojs/)
- [Free and open-source journal management systems](http://oad.simmons.edu/oadwiki/Free_and_open-source_journal_management_software)
- [Peer-review assignments in Moodle](https://docs.moodle.org/19/en/Peer_Review_Assignment_Type)

**Comment by lenfra** [comment]
Intressant funktion för Moodle. Måste kolla om vi har den, alternativt övertala UNT att slänga in den.

--
Lennart Franked

-----Original Message-----

**Comment by dbosk** [comment]
Jag kollade lite snabbt, den finns inte där. Vilka är UNT, har LRC bytt 
namn?

**Comment by lenfra** [comment]
Hittade den, heter Workshop i Moodle

--
Lennart Franked

-----Original Message-----

**Comment by dbosk** [comment]
Added the workshop assignment in Moodle.
